In [4]:
# ============================================================
# 1. IMPORTACIÓN DE LIBRERÍAS
# ============================================================

# PyTorch para redes neuronales
import torch

# Dataset y DataLoader
from torch.utils.data import Dataset, DataLoader

# Manipulación de datos
import numpy as np
import pandas as pd

# Visualización
from matplotlib import pyplot as plt

# Barra de progreso
from tqdm import tqdm

print("Librerías cargadas correctamente.")

Librerías cargadas correctamente.

In [5]:
# ============================================================
# 2. DETECTAR GPU
# ============================================================

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Dispositivo utilizado:", device)

Dispositivo utilizado: cpu

In [6]:
# ============================================================
# 3. CARGAR DATASET
# ============================================================

columnas = [
    'age','workclass','fnlwgt','education','education-num',
    'marital-status','occupation','relationship','race',
    'sex','capital-gain','capital-loss','hours-per-week',
    'native-country','income'
]

# Se cambió "adult.data" por "adult.csv"
data = pd.read_csv(
    "adult.csv", 
    header=None, 
    names=columnas, 
    skipinitialspace=True
)

print("Dataset cargado correctamente.")
print("Dimensiones:", data.shape)

display(data.head())

Dataset cargado correctamente.
Dimensiones: (32562, 15)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
1,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
2,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
3,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
4,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K

In [7]:
# ============================================================
# 4. EXPLORACIÓN INICIAL
# ============================================================

print("Columnas del dataset:")
print(list(data.columns))

print("\nTipos de datos:")
print(data.dtypes)

print("\nValores nulos:")
print(data.isnull().sum())

print("\nValores '?' por columna:")
print((data == '?').sum())

Columnas del dataset:
['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

Tipos de datos:
age               str
workclass         str
fnlwgt            str
education         str
education-num     str
marital-status    str
occupation        str
relationship      str
race              str
sex               str
capital-gain      str
capital-loss      str
hours-per-week    str
native-country    str
income            str
dtype: object

Valores nulos:
age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

Valores '?' por columna:
age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [8]:
# ============================================================
# 5. REEMPLAZAR VALORES '?' POR NaN
# ============================================================

data = data.replace('?', np.nan)

print("Valores '?' convertidos a NaN")

print("\nNulos por columna:")
print(data.isnull().sum())

Valores '?' convertidos a NaN

Nulos por columna:
age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [9]:
# ============================================================
# 6. ELIMINAR COLUMNAS NO NECESARIAS
# ============================================================

data = data.drop(columns=['education','fnlwgt'])

print("Columnas restantes:")
print(list(data.columns))

Columnas restantes:
['age', 'workclass', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country', 'income']

In [10]:
# ============================================================
# 7. IMPUTAR VALORES NULOS
# ============================================================

for col in ['workclass','occupation','native-country']:

    data[col] = data[col].fillna(data[col].mode()[0])

print("Nulos imputados con moda.")

print("\nNulos restantes:")
print(data.isnull().sum())

Nulos imputados con moda.

Nulos restantes:
age               0
workclass         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

In [11]:
# ============================================================
# 8. CONVERTIR TARGET A BINARIO
# ============================================================

data['income'] = data['income'].apply(
    lambda x: 1 if x == '>50K' else 0
)

print("Variable objetivo convertida.")
print(data['income'].value_counts())

Variable objetivo convertida.
income
0    24721
1     7841
Name: count, dtype: int64

In [12]:
# ============================================================
# 9. SELECCIÓN DE FEATURES
# ============================================================

features = [
'age',
'workclass',
'education-num',
'marital-status',
'occupation',
'relationship',
'race',
'sex',
'capital-gain',
'capital-loss',
'hours-per-week',
'native-country'
]

target = 'income'

df = data[features + [target]].copy()

print("Dimensiones:", df.shape)

display(df.head())

Dimensiones: (32562, 13)

,age,workclass,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,age,workclass,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,0
1,90,Private,9,Widowed,Prof-specialty,Not-in-family,White,Female,0,4356,40,United-States,0
2,82,Private,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
3,66,Private,10,Widowed,Prof-specialty,Unmarried,Black,Female,0,4356,40,United-States,0
4,54,Private,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0

In [13]:
# ============================================================
# 10. PREPARAR X e y
# ============================================================

X = df[features].values
y = df[target].values

print("Forma de X:", X.shape)
print("Forma de y:", y.shape)

Forma de X: (32562, 12)
Forma de y: (32562,)